bitloops/bitloops-language

- cli/yarn.lock
- transpiler/src/ast/core/BitloopsVisitor/BitloopsVisitor.ts
- transpiler/src/ast/core/BitloopsVisitor/helpers/test_temp.ts
- transpiler/src/ast/core/index.ts
- transpiler/src/parser/core/grammar/BitloopsParser.g4
- transpiler/src/parser/core/guards/index.ts
- transpiler/src/parser/core/index.ts
Updated core visitor to aggregate different models, and not return the first child.
> Change visitor return method

- transpiler/src/ast/core/BitloopsVisitor/BitloopsVisitor.ts
- transpiler/src/ast/core/BitloopsVisitor/helpers/constDeclaration.ts
- transpiler/src/ast/core/BitloopsVisitor/helpers/expressions.ts
- transpiler/src/ast/core/BitloopsVisitor/helpers/ifStatement.ts
- transpiler/src/ast/core/BitloopsVisitor/helpers/index.ts
- transpiler/src/ast/core/BitloopsVisitor/helpers/statementList.ts
- transpiler/src/ast/core/BitloopsVisitor/helpers/switchStatement.ts
- transpiler/src/ast/core/BitloopsVisitor/helpers/thisDeclaration.ts
- transpiler/src/ast/core/BitloopsVisitor/helpers/variableDeclaration.ts
- transpiler/src/parser/core/grammar/BitloopsParser.g4
Refactored BitloopsVisitor.ts with functions
> refactoring of BitloopsVisitor.ts

- transpiler/src/ast/core/BitloopsVisitor/BitloopsVisitor.ts
- transpiler/src/parser/core/grammar/BitloopsLexer.g4
- transpiler/src/parser/core/grammar/BitloopsParser.g4
> Added errorEvaluation support

- cli/package.json
- cli/src/commands/transpile.ts
- cli/src/utils/inquirer.ts
- cli/yarn.lock
:heavy_check_mark:  added tab completion on path _input_
:screwdriver: fixed errors on build and on runtime
> added tab-completion support and fixed errors 🆗

- cli/package.json
- cli/src/commands/transpile.ts
- cli/src/utils/inquirer.ts
- cli/yarn.lock
Reverts bitloops/bitloops-language#116
> Revert "added tab-completion support and fixed errors 🆗"

- cli/package.json
- cli/src/commands/transpile.ts
- cli/src/utils/inquirer.ts
- cli/yarn.lock
> reimplemented changes 👍

- cli/package.json
- cli/src/index.ts
> [cli] v0.0.20

- documentation/docs/components/value-object.md
> Update value-object documentation

- documentation/docs/introduction/welcome.md
This is a new webpage for our documentation section
Adding a new page to the documentation section
- [ x] Documentation Update (if none of the other choices apply)
- [x ] I have read the [CONTRIBUTING](https://github.com/bitloops/bitloops-language/blob/main/CONTRIBUTING.md) doc
- [ x] I have signed the Bitloops Language CLA (if not, email us: contributor@bitloops.com)
Minor change. Only documentation
> New Docs Page

- documentation/docs/introduction/bigidea.md
This is a page that describes our "big idea".
New page for documentation section
- [ x] Documentation Update (if none of the other choices apply)
- [x ] I have read the [CONTRIBUTING](https://github.com/bitloops/bitloops-language/blob/main/CONTRIBUTING.md) doc
- [x ] I have signed the Bitloops Language CLA (if not, email us: contributor@bitloops.com)
Just a document.
> Create new documentation file for the Intro

- documentation/docusaurus.config.js
- documentation/src/components/HomepageFeatures/index.tsx
- [X ] Bugfix (non-breaking change which fixes an issue)
> [Docs] Fixed category issue

- documentation/docs/introduction/Bitloops_at_a_glance.md
- documentation/docs/introduction/welcome.md
- documentation/docs/learning/_category_.json
- documentation/docs/learning/domain-driven-design.md
- documentation/package-lock.json
- documentation/yarn.lock
- package-lock.json
- yarn.lock
I have tested it locally and it works.
I have added a new section in the Docs Left Hand column, added the text for the domain-driven design page and edited a few other texts. 
- [x ] Documentation Update (if none of the other choices apply)
- [x ] I have read the [CONTRIBUTING](https://github.com/bitloops/bitloops-language/blob/main/CONTRIBUTING.md) doc
- [x ] I have signed the Bitloops Language CLA (if not, email us: …
> I have made several changes to the docs files.

- README.md
> Added Windows command

- transpiler/__tests__/ast/core/builders/fieldDirector.ts
- transpiler/__tests__/ast/core/builders/readModelBuilder.ts
- transpiler/__tests__/ast/core/mocks/readModel.ts
- transpiler/__tests__/ast/core/readModelDeclaration.steps.ts
- transpiler/src/ast/core/BitloopsVisitor/BitloopsVisitor.ts
- transpiler/src/ast/core/BitloopsVisitor/helpers/readModelDeclaration.ts
- transpiler/src/ast/core/intermediate-ast/builders/readModel/ReadModelIdentifierNodeBuilder.ts
- transpiler/src/ast/core/intermediate-ast/builders/readModel/ReadModelNodeBuilder.ts
- transpiler/src/ast/core/intermediate-ast/nodes/Props/PropsIdentifierNode.ts
- transpiler/src/ast/core/intermediate-ast/nodes/readModel/ReadModel.ts
- transpiler/src/ast/core/intermediate-ast/nodes/readModel/ReadModelIdentifierNode.ts
- transpiler/src/helpers/mappings.ts
- transpiler/src/parser/core/grammar/BitloopsParser.g4
- transpiler/src/target/typescript/core/components/readModels/index.ts
- transpiler/src/target/typescript/core/components/repo/repoAdapter.ts
- transpiler/src/target/typescript/core/components/repo/repoPort/helpers/domainIDofRepoPort.ts
- transpiler/src/target/typescript/core/components/repo/repoPort/helpers/mappers.ts
- transpiler/src/target/typescript/core/dependencies.ts
- transpiler/src/target/typescript/core/modelToTargetLanguage.ts
- transpiler/src/target/typescript/helpers/getTargetFileDestination.ts
- transpiler/src/types.ts
> Read model declaration

- transpiler/src/ast/core/BitloopsVisitor/BitloopsVisitor.ts
- transpiler/src/ast/core/BitloopsVisitor/helpers/entityDeclaration.ts
- transpiler/src/ast/core/BitloopsVisitor/helpers/privateMethodDeclaration.ts
- transpiler/src/ast/core/BitloopsVisitor/helpers/publicMethodDeclaration.ts
> fixed metadata

- transpiler/src/target/ast/node-transformers/use-case.ts
> Fix dot value use case

- documentation/docs/learning/test-driven-development.md
> correct some typos

- transpiler/__tests__/ast/setup/builders/repoAdapterDefinitionBuilder.ts
- transpiler/__tests__/ast/setup/builders/repoAdapterExpressionBuilder.ts
- transpiler/__tests__/ast/setup/mocks/repoAdapterDefinition/index.ts
- transpiler/__tests__/ast/setup/mocks/repoAdapterDefinition/repoAdapterDefinition.bl
- transpiler/__tests__/ast/setup/visitor/configInvocation.steps.ts
- transpiler/__tests__/ast/setup/visitor/repoAdapterDefinitions.steps.ts
- transpiler/src/ast/core/BitloopsVisitor/BitloopsVisitor.ts
- transpiler/src/ast/core/BitloopsVisitor/helpers/setup/concretedRepoPort.ts
- transpiler/src/ast/core/BitloopsVisitor/helpers/setup/repoAdapterClassName.ts
- transpiler/src/ast/core/BitloopsVisitor/helpers/setup/repoAdapterDefinition.ts
- transpiler/src/ast/core/BitloopsVisitor/helpers/setup/repoAdapterExpression.ts
- transpiler/src/ast/core/BitloopsVisitor/helpers/setup/repoAdapterOptions.ts
- transpiler/src/ast/core/intermediate-ast/builders/setup/repo/ConcretedRepoPortNodeBuilder.ts
- transpiler/src/ast/core/intermediate-ast/builders/setup/repo/RepoAdapterClassNameNodeBuiler.ts
- transpiler/src/ast/core/intermediate-ast/builders/setup/repo/RepoAdapterDefinitionNodeBuilder.ts
- transpiler/src/ast/core/intermediate-ast/builders/setup/repo/RepoAdapterExpressionNodeBuilder.ts
- transpiler/src/ast/core/intermediate-ast/builders/setup/repo/RepoAdapterOptionsNodeBuilder.ts
- transpiler/src/ast/core/intermediate-ast/nodes/setup/repo/ConcretedRepoPortNode.ts
- transpiler/src/ast/core/intermediate-ast/nodes/setup/repo/RepoAdapterClassNameNode.ts
- transpiler/src/ast/core/intermediate-ast/nodes/setup/repo/RepoAdapterDefinitionNode.ts
- transpiler/src/ast/core/intermediate-ast/nodes/setup/repo/RepoAdapterExpressionNode.ts
- transpiler/src/ast/core/intermediate-ast/nodes/setup/repo/RepoAdapterOptionsNode.ts
- transpiler/src/helpers/mappings.ts
- transpiler/src/parser/core/grammar/BitloopsParser.g4
- transpiler/src/types.ts
> Feature repo adapter definition

- transpiler/__tests__/end-to-end/mocks/setup/app0.mock.ts
- transpiler/__tests__/end-to-end/mocks/setup/fastifyIndex.mock.ts
- transpiler/__tests__/end-to-end/mocks/setup/index.mock.ts
- transpiler/__tests__/end-to-end/mocks/setup/nodemonMock.json
- transpiler/__tests__/end-to-end/mocks/setup/packageMock.json
- transpiler/__tests__/end-to-end/mocks/setup/setup.ts
- transpiler/__tests__/end-to-end/mocks/setup/tsconfigMock.json
> end to end setup test

- transpiler/src/helpers/bitloopsPrimitiveToLang.ts
- transpiler/src/helpers/supportedLanguages.ts
- transpiler/src/target/index.ts
- transpiler/src/target/targetCoreCreator.ts
- transpiler/src/target/targetSetupCreator.ts
- transpiler/src/target/types.ts
- transpiler/src/target/typescript/core/index.ts
- transpiler/src/target/typescript/setup/SetupTypeScript.ts
- transpiler/src/target/typescript/setup/index.ts
> add factory method

- transpiler/__tests__/target/typescript/core/mocks/repoAdapter/index.ts
- transpiler/__tests__/target/typescript/core/mocks/repoAdapter/multipleReposTodoWriteRepo.mock.ts
- transpiler/src/helpers/typeGuards.ts
- transpiler/src/target/typescript/core/components/repo/helpers/mongo/aggregateCrudRepo.ts
- transpiler/src/target/typescript/core/components/repo/helpers/repoAdapterBody.ts
- transpiler/src/target/typescript/setup/SetupTypeScript.ts
- transpiler/src/target/typescript/setup/helpers.ts
- transpiler/src/target/typescript/setup/repos/index.ts
- transpiler/src/types.ts
> Fix identifier type and adapter dis 

- .github/workflows/ci.yml
> Fixed path in CI workflow

- .github/workflows/ci.yml
- transpiler/__tests__/ast/core/dtoDeclaration.steps.ts
- transpiler/__tests__/ast/core/getClass.steps.ts
- transpiler/__tests__/ast/core/isInstanceOf.steps.ts
- transpiler/__tests__/ast/core/mocks/repoPort.ts
- transpiler/__tests__/ast/core/propsDeclaration.steps.ts
- transpiler/__tests__/ast/core/structDeclaration.steps.ts
- transpiler/__tests__/ast/core/toString.steps.ts
- transpiler/package.json
- transpiler/src/Transpiler.ts
- transpiler/src/ast/core/guards/index.ts
- transpiler/src/index.ts
- transpiler/src/parser/core/VerboseErrorListener.ts
- transpiler/src/parser/core/guards/index.ts
- transpiler/src/parser/core/index.ts
- transpiler/src/parser/core/types.ts
- transpiler/yarn.lock
> Export bl code to model

- cli/package.json
- cli/src/index.ts
- cli/yarn.lock
> Update cli version

- boilerplate/ts/core/package.json
- boilerplate/ts/core/src/Container.ts
- boilerplate/ts/core/src/application/AppError.ts
- boilerplate/ts/core/src/domain/DomainError.ts
- boilerplate/ts/core/src/domain/commands/ICommandBus.ts
- boilerplate/ts/core/src/domain/events/Events.ts
- boilerplate/ts/core/src/domain/messages/IMessage.ts
- boilerplate/ts/core/src/index.ts
- boilerplate/ts/core/src/infra/command-bus/externalCommandBus.ts
- boilerplate/ts/core/src/infra/command-bus/index.ts
- boilerplate/ts/core/src/infra/message-bus/InProcessMessageBus.ts
- boilerplate/ts/core/src/infra/message-bus/NatsMessageBus.ts
- boilerplate/ts/core/yarn.lock
- examples/todo/ts-target/src/bounded-contexts/todo/todo/domain/errors/TitleOutofBoundsError.ts
> Fix command

- boilerplate/ts/core/src/domain/standard-values/common/index.ts
- boilerplate/ts/core/src/domain/standard-values/currency/Currency.ts
- boilerplate/ts/core/src/domain/standard-values/currency/errors/index.ts
- boilerplate/ts/core/src/domain/standard-values/currency/rules/index.ts
- boilerplate/ts/core/src/domain/standard-values/index.ts
- boilerplate/ts/core/src/index.ts
> added CurrencyVO

- transpiler/__tests__/ast/core/builders/evaluationDirector.ts
- transpiler/__tests__/ast/core/mocks/entity/entityCheckReturnOkErrorStatement.bl
- transpiler/__tests__/ast/core/mocks/entity/entityMethodWithVoidErrorType.bl
- transpiler/__tests__/ast/core/mocks/entity/entityPrivateMethodOkErrorReturnType.bl
- transpiler/__tests__/ast/core/mocks/entity/entityPrivatePublicMethod.bl
- transpiler/__tests__/ast/core/mocks/entity/entityReturnDomainError.bl
- transpiler/__tests__/ast/core/mocks/evaluation/entityEvaluation.ts
- transpiler/__tests__/ast/core/mocks/evaluation/evaluation.ts
- transpiler/__tests__/ast/core/mocks/evaluation/valueObjectEvaluation.ts
- transpiler/__tests__/ast/core/mocks/rootEntity/rootEntityPrivateMethodOkErrorReturnType.bl
- transpiler/__tests__/ast/core/mocks/rootEntity/rootEntityPrivatePublicMethod.bl
- transpiler/__tests__/ast/core/mocks/rootEntity/rootEntityReturnDomainError.bl
- transpiler/__tests__/ast/core/mocks/useCase.ts
- transpiler/__tests__/end-to-end/mocks/rest-controller/todo-demo-create-controller.bl
- transpiler/__tests__/target/typescript/core/builders/evaluation.ts
- transpiler/__tests__/target/typescript/core/mocks/expression/evaluation.ts
- transpiler/src/ast/core/BitloopsVisitor/BitloopsVisitor.ts
- transpiler/src/ast/core/BitloopsVisitor/helpers/expression/evaluation/entityConstructorEvaluation.ts
- transpiler/src/ast/core/BitloopsVisitor/helpers/expression/evaluation/index.ts
- transpiler/src/ast/core/BitloopsVisitor/helpers/index.ts
- transpiler/src/ast/core/intermediate-ast/builders/expressions/evaluation/EntityConstructorEvaluationNodeBuilder.ts
- transpiler/src/ast/core/intermediate-ast/nodes/Expression/Evaluation/EntityConstructorEvaluationNode.ts
- transpiler/src/helpers/mappings.ts
- transpiler/src/parser/core/grammar/BitloopsParser.g4
- transpiler/src/target/typescript/core/components/statements/expression/evaluation/entityConstructorEvaluation.ts
- transpiler/src/target/typescript/core/components/statements/expression/evaluation/index.ts
- transpiler/src/target/typescript/core/modelToTargetLanguage.ts
- transpiler/src/target/typescript/core/type-identifiers/evaluation.ts
- transpiler/src/types.ts
> Fix entity and value object evaluation(add create)

- transpiler/__tests__/target/typescript/core/mocks/readModel/classReadModel.ts
- transpiler/__tests__/target/typescript/core/mocks/readModel/nameReadModel.ts
- transpiler/__tests__/target/typescript/core/mocks/repoAdapter/multipleReposTodoReadRepo.mock.ts
- transpiler/__tests__/target/typescript/core/mocks/repoAdapter/todoReadRepo.mock.ts
- transpiler/src/target/typescript/core/components/read-model/index.ts
- transpiler/src/target/typescript/core/components/repo/helpers/mongo/readModelCrudRepo.ts
> make read model class

- transpiler/__tests__/end-to-end/mocks/rest-controller/todo-demo-create-controller.mock.ts
- transpiler/__tests__/target/typescript/core/builders/controllers/graphqlDirector.ts
- transpiler/__tests__/target/typescript/core/builders/controllers/restDirector.ts
- transpiler/__tests__/target/typescript/core/mocks/controllers/restController.ts
- transpiler/src/ast/core/intermediate-ast/ node-transformers/ControllerNodeTransformer.ts
- transpiler/src/ast/core/intermediate-ast/IntermediateASTToAST.ts
- transpiler/src/ast/core/intermediate-ast/builders/controllers/ControllerBusDependenciesNodeBuilder.ts
- transpiler/src/ast/core/intermediate-ast/builders/controllers/restController/RESTControllerNodeBuilder.ts
- transpiler/src/ast/core/intermediate-ast/nodes/controllers/ControllerBusDependenciesNode.ts
- transpiler/src/ast/core/intermediate-ast/nodes/controllers/ControllerNode.ts
- transpiler/src/ast/core/intermediate-ast/nodes/controllers/graphql/GraphQLControllerExecuteNode.ts
- transpiler/src/ast/core/intermediate-ast/nodes/controllers/graphql/GraphQLControllerNode.ts
- transpiler/src/ast/core/intermediate-ast/nodes/controllers/restController/RESTControllerExecuteNode.ts
- transpiler/src/ast/core/intermediate-ast/nodes/controllers/restController/RESTControllerNode.ts
- transpiler/src/helpers/mappings.ts
- transpiler/src/target/typescript/ast/node-transformers/controllers/index.ts
- transpiler/src/target/typescript/core/components/controllers/graphql/index.ts
- transpiler/src/target/typescript/core/components/controllers/helpers/buildFieldsFromDependencies.ts
- transpiler/src/target/typescript/core/components/controllers/rest/index.ts
- transpiler/src/target/typescript/core/components/domain-event-handler/handlerAttributesAndConstructor.ts
- transpiler/src/types.ts
> Prepend await

- transpiler/__tests__/ast/core/builders/expressionDirector.ts
- transpiler/__tests__/ast/core/mocks/expression.ts
- transpiler/__tests__/target/typescript/core/builders/expression.ts
- transpiler/__tests__/target/typescript/core/mocks/expression/expression.ts
- transpiler/src/ast/core/BitloopsVisitor/BitloopsVisitor.ts
- transpiler/src/ast/core/BitloopsVisitor/helpers/expression/literal/regexLiteral.ts
- transpiler/src/ast/core/BitloopsVisitor/helpers/index.ts
- transpiler/src/ast/core/intermediate-ast/builders/expressions/literal/RegexLiteralNodeBuilder.ts
- transpiler/src/ast/core/intermediate-ast/nodes/Expression/Literal/RegexLiteralNode.ts
- transpiler/src/helpers/mappings.ts
- transpiler/src/parser/core/grammar/BitloopsLexer.g4
- transpiler/src/parser/core/grammar/BitloopsParser.g4
- transpiler/src/target/typescript/core/components/statements/expression/literalExpression.ts
- transpiler/src/target/typescript/core/type-identifiers/literal.ts
- transpiler/src/types.ts
> add regex e-2-e

- transpiler/__tests__/ast/core/builders/methods/PrivateMethodBuilder.ts
- transpiler/__tests__/ast/core/mocks/entity/entityPrivatePublicMethod.bl
- transpiler/__tests__/ast/core/mocks/rootEntity/rootEntityPrivatePublicMethod.bl
- transpiler/__tests__/ast/core/mocks/valueObject/valueObjectWithPrivateMethod.bl
- transpiler/src/ast/core/BitloopsVisitor/BitloopsVisitor.ts
- transpiler/src/ast/core/BitloopsVisitor/helpers/index.ts
- transpiler/src/ast/core/BitloopsVisitor/helpers/privateMethodDeclaration.ts
- transpiler/src/ast/core/BitloopsVisitor/helpers/publicMethodDeclaration.ts
- transpiler/src/ast/core/BitloopsVisitor/helpers/returnMethodType.ts
- transpiler/src/ast/core/intermediate-ast/builders/methods/PublicMethodDeclarationNodeBuilder.ts
- transpiler/src/ast/core/intermediate-ast/nodes/Expression/IdentifierExpression.ts
- transpiler/src/ast/core/intermediate-ast/nodes/Expression/MemberDot/MemberDotExpression.ts
- transpiler/src/helpers/typeGuards.ts
- transpiler/src/parser/core/grammar/BitloopsParser.g4
- transpiler/src/target/typescript/ast/node-transformers/generic/appendDotValue.ts
- transpiler/src/target/typescript/core/components/domain/domainPrivateMethod.ts
- transpiler/src/target/typescript/core/components/domain/domainPublicMethod.ts
- transpiler/src/types.ts
> Fix methods return type

- transpiler/__tests__/ast/core/builders/execute/executeDirector.ts
- transpiler/src/ast/core/intermediate-ast/ node-transformers/ExecuteNodeTransformer.ts
- transpiler/src/ast/core/intermediate-ast/ node-transformers/generic/AddApplicationUnexpectedErrorTransformer.ts
- transpiler/src/ast/core/intermediate-ast/IntermediateASTToAST.ts
- transpiler/src/ast/core/intermediate-ast/directors/ErrorIdentifiersNodeBuilderDirector.ts
- transpiler/src/ast/core/intermediate-ast/nodes/ErrorIdentifiers/ErrorIdentifiersNode.ts
- transpiler/src/ast/core/intermediate-ast/nodes/ExecuteNode.ts
- transpiler/src/ast/core/intermediate-ast/nodes/returnOkErrorType/ReturnOkErrorTypeNode.ts
- transpiler/src/helpers/architectureLayers.ts
- transpiler/src/helpers/isBitloopsStandardApplicationError.ts
- transpiler/src/helpers/mappings.ts
- transpiler/src/target/typescript/core/dependencies.ts
> added application unexpected error in execute declaration response

- boilerplate/ts/core/package.json
- boilerplate/ts/core/src/index.ts
- boilerplate/ts/infra/nest-jetstream/package.json
- boilerplate/ts/infra/nest-jetstream/src/buses/nats-pubsub-query-bus.ts
- boilerplate/ts/infra/nest-jetstream/yarn.lock
> Feature update query in packages

- examples/todo/bl-source-new/marketing/marketing/ports/repo.ports.bl
- transpiler/__tests__/target/typescript/core/mocks/command/insertPINCommand.mock.ts
- transpiler/__tests__/target/typescript/core/mocks/domain-event/accountCreatedDomainEvent.mock.ts
- transpiler/__tests__/target/typescript/core/mocks/integration-event/moneyDepositedIntegrationEvent.mock.ts
- transpiler/__tests__/target/typescript/core/mocks/integration-event/moneyDepositedIntegrationEventTwoMappers.mock.ts
- transpiler/__tests__/target/typescript/core/mocks/query/getCustomerByIdQuery.mock.ts
- transpiler/src/helpers/mappings.ts
- transpiler/src/target/typescript/core/components/command/index.ts
- transpiler/src/target/typescript/core/components/domain-event/index.ts
- transpiler/src/target/typescript/core/components/integration-event/index.ts
- transpiler/src/target/typescript/core/components/metadata/index.ts
- transpiler/src/target/typescript/core/components/query/index.ts
- transpiler/src/target/typescript/core/modelToTargetLanguage.ts
- transpiler/src/types.ts
> Feature update command queries events class

- transpiler/__tests__/ast/core/builders/statement/returnStatementBuilder.ts
- transpiler/__tests__/ast/core/mocks/statements/returnStatement.ts
- transpiler/__tests__/target/typescript/core/builders/statement/returnDirector.ts
- transpiler/__tests__/target/typescript/core/mocks/statements/return.ts
- transpiler/src/ast/core/BitloopsVisitor/BitloopsVisitor.ts
- transpiler/src/ast/core/intermediate-ast/builders/statements/ReturnStatementBuilder.ts
- transpiler/src/parser/core/grammar/BitloopsParser.g4
- transpiler/src/target/typescript/core/components/statements/return.ts
- transpiler/src/types.ts
> added empty return support

- examples/todo/bl-source-new/iam/authentication/application/command-handlers/change-email.handler.bl
- examples/todo/bl-source-new/marketing/marketing/application/command-handlers/change-user-email.command-handler.bl
- examples/todo/bl-source-new/marketing/marketing/application/command-handlers/increment-todos.command-handler.bl
- examples/todo/bl-source-new/marketing/marketing/application/command-handlers/send-email.command-handler.bl
- examples/todo/bl-source-new/marketing/marketing/application/event-handlers/domain/todo-completions-incremented.domain-event-handler.bl
- examples/todo/bl-source-new/marketing/marketing/domain/services/marketing-notification.domain-service.bl
- examples/todo/bl-source-new/todo/todo/application/command-handlers/add-todo.command-handler.bl
- examples/todo/bl-source-new/todo/todo/application/command-handlers/complete-todo.command-handler.bl
- examples/todo/bl-source-new/todo/todo/application/command-handlers/modify-todo-title.command-handler.bl
- examples/todo/bl-source-new/todo/todo/application/command-handlers/uncomplete-todo.command-handler.bl
- examples/todo/bl-source-new/todo/todo/application/errors/errors.bl
- examples/todo/bl-source-new/todo/todo/application/query-handlers/get-all-todos.query-handler.bl
- transpiler/__tests__/ast/core/mocks/statements/returnErrorStatement.ts
- transpiler/__tests__/ast/core/returnErrorStatement.steps.ts
- transpiler/src/ast/core/BitloopsVisitor/BitloopsVisitor.ts
- transpiler/src/parser/core/grammar/BitloopsParser.g4
- transpiler/src/target/typescript/ast/node-transformers/generic/appendDotValue.ts
> added return error statement

- transpiler/__tests__/target/typescript/core/mocks/commandHandler/WithdrawMoneyCommandHandler.mock.ts
- transpiler/__tests__/target/typescript/core/mocks/domain-event-handler/sendEmailHandler.mock.ts
- transpiler/__tests__/target/typescript/core/mocks/integration-event-handler/handlerWithDependency.mock.ts
- transpiler/__tests__/target/typescript/core/mocks/integration-event-handler/handlerWithEventFromPackage.mock.ts
- transpiler/__tests__/target/typescript/core/mocks/integration-event-handler/index.ts
- transpiler/__tests__/target/typescript/core/mocks/integration-event-handler/moneyDepositedIntegrationHandler.mock.ts
- transpiler/__tests__/target/typescript/core/mocks/queryHandler/GetCustomerByIDQueryHandler.mock.ts
- transpiler/src/target/typescript/core/components/commandHandler/index.ts
- transpiler/src/target/typescript/core/components/domain-event-handler/domainEventHandler.ts
- transpiler/src/target/typescript/core/components/integration-event/integrationEventHandler.ts
- transpiler/src/target/typescript/core/components/integration-event/integrationEventParameter.ts
- transpiler/src/target/typescript/core/components/queryHandler/index.ts
- transpiler/src/target/typescript/helpers/packagesEventMapping.ts
> Feature event handler pacjage events

- transpiler/__tests__/ast/core/builders/execute/executeDirector.ts
- transpiler/__tests__/ast/core/builders/statement/statementDirector.ts
- transpiler/__tests__/ast/core/builders/statement/variableDeclarationDirector.ts
- transpiler/__tests__/ast/core/mocks/domainRule.ts
- transpiler/__tests__/ast/core/mocks/integrationEvent/integrationEvent.ts
- transpiler/__tests__/ast/core/mocks/statements/constDeclaration.ts
- transpiler/__tests__/ast/core/mocks/statements/variableDeclaration.ts
- transpiler/__tests__/ast/core/mocks/valueObject/valueObject.ts
- transpiler/__tests__/target/typescript/core/builders/statement/variableDeclaration.ts
- transpiler/__tests__/target/typescript/core/mocks/statements/statements.ts
- transpiler/src/ast/core/BitloopsVisitor/helpers/variableDeclaration.ts
- transpiler/src/ast/core/intermediate-ast/builders/statements/variableDeclaration.ts
- transpiler/src/parser/core/grammar/BitloopsParser.g4
- transpiler/src/target/typescript/core/components/statements/variableDeclaration.ts
> added variable declaration without expression

- examples/README.md
Major changes to the readme. Includes Antonis initial work on the ToDo app example.
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you …
> Update Example Readme

- examples/README.md
> added minor fixes

- transpiler/__tests__/ast/core/builders/methodDefinitionDirector.ts
- transpiler/__tests__/ast/core/mocks/methodDefinitionList.ts
- transpiler/__tests__/ast/core/mocks/repoPort.ts
- transpiler/__tests__/ast/core/mocks/servicePort.ts
- transpiler/__tests__/ast/core/repoPortDeclaration.steps.ts
- transpiler/__tests__/ast/core/servicePortDeclaration.steps.ts
- transpiler/__tests__/target/typescript/core/builders/methodDefinitionNodeBuilderDirector.ts
- transpiler/__tests__/target/typescript/core/builders/repoPortNodeBuilderDirector.ts
- transpiler/__tests__/target/typescript/core/mocks/service-port/index.ts
- transpiler/__tests__/target/typescript/core/mocks/service-port/servicePortTwoDefinitions.mock.ts
- transpiler/src/ast/core/BitloopsVisitor/helpers/methodDefinition.ts
- transpiler/src/ast/core/intermediate-ast/ node-transformers/RepoPortNodeTransformer.ts
- transpiler/src/ast/core/intermediate-ast/ node-transformers/ServicePortNodeTransformer.ts
- transpiler/src/ast/core/intermediate-ast/ node-transformers/generic/AddApplicationUnexpectedErrorTransformer.ts
- transpiler/src/ast/core/intermediate-ast/IntermediateASTToAST.ts
- transpiler/src/ast/core/intermediate-ast/builders/methodDefinition/methodDefinitionNodeBuilder.ts
- transpiler/src/ast/core/intermediate-ast/nodes/ExecuteNode.ts
- transpiler/src/ast/core/intermediate-ast/nodes/method-definitions/MethodDefinitionListNode.ts
- transpiler/src/ast/core/intermediate-ast/nodes/method-definitions/MethodDefinitionNode.ts
- transpiler/src/ast/core/intermediate-ast/nodes/repo-port/RepoPortNode.ts
- transpiler/src/ast/core/intermediate-ast/nodes/service-port/ServicePortNode.ts
- transpiler/src/helpers/typeGuards.ts
- transpiler/src/parser/core/grammar/BitloopsParser.g4
- transpiler/src/target/typescript/core/components/definition-methods/index.ts
- transpiler/src/target/typescript/core/components/okkErrorReturnType.ts
- transpiler/src/types.ts
> Feature change ports to either response

- transpiler/__tests__/end-to-end/domainService.steps.ts
- transpiler/__tests__/end-to-end/mocks/domain-service/index.ts
- transpiler/__tests__/end-to-end/mocks/domain-service/todo-marketing-domain-service.bl
- transpiler/__tests__/end-to-end/mocks/domain-service/todo-marketing-domain-service.mock.ts
- transpiler/src/target/typescript/ast/index.ts
- transpiler/src/target/typescript/ast/node-transformers/domainMethods/index.ts
> initial commit

- transpiler/__tests__/target/typescript/core/builders/repoPortNodeBuilderDirector.ts
- transpiler/__tests__/target/typescript/core/builders/servicePortNodeBuilderDirector.ts
- transpiler/__tests__/target/typescript/core/mocks/package/packagePort.ts
- transpiler/__tests__/target/typescript/core/mocks/repoPort/index.ts
- transpiler/__tests__/target/typescript/core/mocks/repoPort/readPortWithDefinitions.mock.ts
- transpiler/__tests__/target/typescript/core/mocks/repoPort/writePortWithDefinitions.mock.ts
- transpiler/__tests__/target/typescript/core/mocks/repoPort/writeRepoPortNoDefinitions.mock.ts
- transpiler/__tests__/target/typescript/core/mocks/repoPort/writeRepoPortVOGetter.mock.ts
- transpiler/__tests__/target/typescript/core/mocks/repoPort/writeRepoPortVONoGetter.mock.ts
- transpiler/__tests__/target/typescript/core/mocks/service-port/index.ts
- transpiler/__tests__/target/typescript/core/mocks/service-port/servicePortTwoDefinitions.mock.ts
- transpiler/src/target/typescript/core/components/definition-methods/index.ts
- transpiler/src/target/typescript/core/components/repo/repoPort/helpers/withMethodsPort.ts
- transpiler/src/target/typescript/core/components/repo/repoPort/repoPort.ts
> Fix repo either responses

- transpiler/__tests__/end-to-end/mocks/semantic-errors/Todo/Todo/controllers.bl
- transpiler/__tests__/end-to-end/mocks/semantic-errors/Todo/Todo/graphQLController.bl
- transpiler/__tests__/end-to-end/mocks/semantic-errors/Todo/Todo/repoPorts.bl
- transpiler/__tests__/end-to-end/mocks/semantic-errors/Todo/Todo/setupControllerNotFound.bl
- transpiler/__tests__/end-to-end/mocks/semantic-errors/Todo/Todo/setupRepoAdapterNotFound.bl
- transpiler/__tests__/end-to-end/mocks/semantic-errors/Todo/Todo/setupRepoConnectionNotFound.bl
- transpiler/__tests__/end-to-end/mocks/semantic-errors/Todo/Todo/setupRouterNotFound.bl
- transpiler/__tests__/end-to-end/mocks/semantic-errors/Todo/Todo/useCases.bl
- transpiler/__tests__/end-to-end/mocks/semantic-errors/commandsQueriesNotFound.bl
- transpiler/__tests__/end-to-end/mocks/semantic-errors/domainIntegrationEventsNotFound.bl
- transpiler/__tests__/end-to-end/mocks/semantic-errors/domainServiceNotFound.bl
- transpiler/__tests__/end-to-end/mocks/semantic-errors/semantic-errors.ts
- transpiler/__tests__/end-to-end/mocks/semantic-errors/servicePort.bl
- transpiler/__tests__/end-to-end/mocks/semantic-errors/servicePortNotFound.bl
- transpiler/__tests__/end-to-end/semantic-errors.steps.ts
- transpiler/src/ast/core/intermediate-ast/IntermediateASTValidator.ts
- transpiler/src/ast/core/intermediate-ast/nodes/Expression/Evaluation/DomainServiceEvaluationNode.ts
- transpiler/src/ast/core/intermediate-ast/nodes/domain-service/DomainServiceNode.ts
- transpiler/src/ast/core/intermediate-ast/validators/domainServiceEvaluationError.ts
- transpiler/src/ast/core/intermediate-ast/validators/index.ts
> Add elements to validator

- transpiler/__tests__/target/typescript/core/mocks/expression/evaluation.ts
> fixed evaluation test for readModel

- transpiler/__tests__/target/typescript/core/mocks/domain/valueObject.ts
- transpiler/src/target/typescript/core/components/domain/generateGetters.ts
Fixed issue with id inside a value object
> fixed issue with not be able to create an id inside a value object

- transpiler/__tests__/end-to-end/mocks/domain-service/todo-marketing-domain-service.mock.ts
- transpiler/__tests__/target/typescript/core/builders/domainServiceBuilder.ts
- transpiler/__tests__/target/typescript/core/builders/methods/publicMethodBuilderDirector.ts
- transpiler/__tests__/target/typescript/core/builders/statement/constDeclaration.ts
- transpiler/__tests__/target/typescript/core/builders/statement/statementDirector.ts
- transpiler/__tests__/target/typescript/core/mocks/domain-service/domainServiceWithRepoCall.mock.ts
- transpiler/__tests__/target/typescript/core/mocks/domain-service/index.ts
- transpiler/src/ast/core/intermediate-ast/IntermediateASTTree.ts
- transpiler/src/target/typescript/ast/node-transformers/domainMethods/index.ts
> Feature add dot value domain service

- transpiler/__tests__/target/typescript/core/mocks/domain/entity.ts
- transpiler/__tests__/target/typescript/core/mocks/domain/files/TodoEntity.mock.ts
- transpiler/src/target/typescript/core/components/domain/generateGetters.ts
- transpiler/src/target/typescript/core/components/entity-values/fromToPrimitives.ts
- transpiler/src/target/typescript/core/components/entity/index.ts
- transpiler/src/target/typescript/core/components/root-entity/index.ts
> Fix from to primitives UUID

- transpiler/src/ast/core/intermediate-ast/IntermediateASTTree.ts
- transpiler/src/ast/core/intermediate-ast/nodes/BitloopsPrimaryType/BitloopsIdentifierTypeNode.ts
- transpiler/src/ast/core/intermediate-ast/nodes/BitloopsPrimaryType/BitloopsPrimaryTypeNode.ts
- transpiler/src/ast/core/intermediate-ast/nodes/DomainEventHandler/DomainEventHandlerDeclarationNode.ts
- transpiler/src/ast/core/intermediate-ast/nodes/Entity/EntityValuesNode.ts
- transpiler/src/ast/core/intermediate-ast/nodes/Expression/Evaluation/DomainEvaluation/DomainEvaluation.ts
- transpiler/src/ast/core/intermediate-ast/nodes/Expression/Evaluation/EntityEvaluation.ts
- transpiler/src/ast/core/intermediate-ast/nodes/Expression/Evaluation/EvaluationNode.ts
- transpiler/src/ast/core/intermediate-ast/nodes/Expression/ExpressionNode.ts
- transpiler/src/ast/core/intermediate-ast/nodes/ParameterList/ParameterNode.ts
- transpiler/src/ast/core/intermediate-ast/nodes/RootEntity/RootEntityDeclarationNode.ts
- transpiler/src/ast/core/intermediate-ast/nodes/UseCase/UseCaseNode.ts
- transpiler/src/ast/core/intermediate-ast/nodes/command/CommandHandlerNode.ts
- transpiler/src/ast/core/intermediate-ast/nodes/integration-event/IntegrationEventHandlerDeclarationNode.ts
- transpiler/src/ast/core/intermediate-ast/nodes/methods/PublicMethodDeclarationListNode.ts
- transpiler/src/ast/core/intermediate-ast/nodes/methods/PublicMethodDeclarationNode.ts
- transpiler/src/ast/core/intermediate-ast/nodes/query/QueryHandlerNode.ts
- transpiler/src/ast/core/intermediate-ast/nodes/repo-port/RepoPortNode.ts
- transpiler/src/helpers/typeGuards.ts
- transpiler/src/target/typescript/ast/node-transformers/commandHandler.ts
- transpiler/src/target/typescript/ast/node-transformers/domainEventHandler.ts
- transpiler/src/target/typescript/ast/node-transformers/generic/appendDotValue.ts
- transpiler/src/target/typescript/ast/node-transformers/integrationEventHandler.ts
- transpiler/src/target/typescript/ast/node-transformers/queryHandler.ts
> Append value domain method results

- transpiler/__tests__/end-to-end/mocks/domain-service/todo-marketing-domain-service.mock.ts
- transpiler/__tests__/target/typescript/core/mocks/domain-service/domainServiceWithRepoCall.mock.ts
- transpiler/src/ast/core/intermediate-ast/nodes/domain-service/DomainServiceNode.ts
- transpiler/src/ast/core/intermediate-ast/nodes/methods/PrivateMethodDeclarationListNode.ts
- transpiler/src/ast/core/intermediate-ast/nodes/methods/PublicMethodDeclarationListNode.ts
- transpiler/src/target/typescript/ast/index.ts
- transpiler/src/target/typescript/ast/node-transformers/domainMethods/index.ts
- transpiler/src/target/typescript/ast/node-transformers/domainServiceTransformer/index.ts
- transpiler/src/target/typescript/ast/node-transformers/generic/appendDotValue.ts
> Feature add await domain service

- boilerplate/ts/core/src/domain/commands/Command.ts
- boilerplate/ts/core/src/domain/commands/ICommandBus.ts
- boilerplate/ts/core/src/domain/events/IDomainEvent.ts
- boilerplate/ts/core/src/domain/events/IIntegrationEvent.ts
- boilerplate/ts/core/src/domain/messages/IMessage.ts
- boilerplate/ts/core/src/domain/queries/IQuery.ts
- boilerplate/ts/core/src/index.ts
Refactor metadata of events & add domain event props generic type
> Refactor boilerplate metadata

- boilerplate/ts/core/package.json
- boilerplate/ts/core/src/domain/commands/Command.ts
- boilerplate/ts/core/src/domain/events/IDomainEvent.ts
- boilerplate/ts/core/src/domain/events/IEvent.ts
- boilerplate/ts/core/src/domain/events/IIntegrationEvent.ts
- boilerplate/ts/core/src/domain/messages/IMessage.ts
- boilerplate/ts/core/src/domain/queries/IQuery.ts
- boilerplate/ts/core/src/domain/queries/IQueryBus.ts
- boilerplate/ts/infra/nest-jetstream/package.json
- boilerplate/ts/infra/nest-jetstream/src/buses/nats-pubsub-command-bus.ts
- boilerplate/ts/infra/nest-jetstream/src/buses/nats-pubsub-integration-events-bus.ts
- boilerplate/ts/infra/nest-jetstream/src/buses/nats-pubsub-query-bus.ts
- boilerplate/ts/infra/nest-jetstream/src/buses/nats-streaming-command-bus.ts
- boilerplate/ts/infra/nest-jetstream/src/buses/nats-streaming-domain-event-bus.ts
- boilerplate/ts/infra/nest-jetstream/src/buses/nats-streaming-integration-event-bus.ts
- boilerplate/ts/infra/nest-jetstream/yarn.lock
> Feature remove async local storage

- cli/package.json
- cli/yarn.lock
- transpiler/package.json
> updated packages

- cli/package.json
- cli/src/version.ts
- cli/yarn.lock
> updated cli package

- transpiler/__tests__/ast/core/builders/evaluationDirector.ts
- transpiler/__tests__/ast/core/mocks/evaluation/evaluation.ts
- transpiler/__tests__/target/typescript/core/builders/evaluation.ts
- transpiler/__tests__/target/typescript/core/mocks/expression/evaluation.ts
- transpiler/src/ast/core/BitloopsVisitor/BitloopsVisitor.ts
- transpiler/src/ast/core/BitloopsVisitor/helpers/expression/evaluation/valueObejctConstructorEvaluation.ts
- transpiler/src/ast/core/intermediate-ast/builders/expressions/evaluation/ValueObjectConstructorEvaluationNodeBuilder.ts
- transpiler/src/ast/core/intermediate-ast/nodes/Expression/Evaluation/ValueObjectConstructorEvaluationNode.ts
- transpiler/src/helpers/mappings.ts
- transpiler/src/parser/core/grammar/BitloopsParser.g4
- transpiler/src/target/typescript-nest/core/components/statements/expression/evaluation/index.ts
- transpiler/src/target/typescript-nest/core/components/statements/expression/evaluation/valueObjectConstructorEvaluation.ts
- transpiler/src/target/typescript-nest/core/modelToTargetLanguage.ts
- transpiler/src/target/typescript-nest/core/type-identifiers/evaluation.ts
- transpiler/src/types.ts
> Added value object constructor evaluation

- transpiler/__tests__/end-to-end/mocks/symbol-table/symbol-table.ts
- transpiler/package.json
- transpiler/src/semantic-analysis/type-inference/SymbolTable.ts
> added fileId to the scope of keyword

- transpiler/__tests__/end-to-end/mocks/symbol-table/entity-evaluation.bl
- transpiler/__tests__/end-to-end/mocks/symbol-table/symbol-table.ts
- transpiler/src/ast/core/intermediate-ast/nodes/BitloopsPrimaryType/ArrayPrimaryTypeNode.ts
- transpiler/src/ast/core/intermediate-ast/nodes/BitloopsPrimaryType/BitloopsIdentifierTypeNode.ts
- transpiler/src/ast/core/intermediate-ast/nodes/BitloopsPrimaryType/BitloopsPrimaryTypeNode.ts
- transpiler/src/ast/core/intermediate-ast/nodes/BitloopsPrimaryType/BuildInClassTypeNode.ts
- transpiler/src/ast/core/intermediate-ast/nodes/BitloopsPrimaryType/PrimitiveTypeNode.ts
- transpiler/src/ast/core/intermediate-ast/nodes/BitloopsPrimaryType/StandardValueTypeNode.ts
- transpiler/src/ast/core/intermediate-ast/nodes/Entity/EntityValuesNode.ts
- transpiler/src/ast/core/intermediate-ast/nodes/methods/PrivateMethodDeclarationNode.ts
- transpiler/src/types.ts
> Adds to symbol table

- cli/src/commands/generate-nest-project/generate-nest-project.ts
- cli/src/commands/generate-nest-project/helpers/generate-project.ts
- cli/src/commands/generate-nest-project/helpers/npm-install-nestjs-cli.ts
- cli/src/commands/generate-nest-project/helpers/npm-list-nestjs-cli.ts
> Fix cli nestjs cli

- transpiler/package.json
- transpiler/src/ast/core/intermediate-ast/nodes/Entity/EntityValuesNode.ts
- transpiler/src/ast/core/intermediate-ast/nodes/Expression/MemberDot/MemberDotExpressionNode.ts
> removed logs

- transpiler/__tests__/target/typescript/core/mocks/commandHandler/SendEmailCommandHandler.mock.ts
- transpiler/__tests__/target/typescript/core/mocks/commandHandler/WithdrawMoneyCommandHandler.mock.ts
- transpiler/package.json
- transpiler/src/target/typescript-nest/core/components/commandHandler/index.ts
- transpiler/src/target/typescript-nest/core/components/execute.ts
- transpiler/src/target/typescript-nest/helpers/systemEventsDecorator.ts
> added decorator to command handler

- boilerplate/ts/core/package.json
- boilerplate/ts/core/src/Either.ts
- boilerplate/ts/core/src/domain/events/IDomainEvent.ts
- boilerplate/ts/core/src/domain/events/IEvent.ts
- boilerplate/ts/core/src/domain/events/IIntegrationEvent.ts
> fixed ok issue and added payload to IEvent

- boilerplate/ts/core/package.json
- boilerplate/ts/core/src/application/ICRUDRepoPort.ts
- boilerplate/ts/core/src/domain/AggregateRoot.ts
- boilerplate/ts/core/src/errors/repository/ConcurrencyOrNotFoundError.ts
- boilerplate/ts/core/src/index.ts
> D2 c 714 concurency problem backend

- boilerplate/ts/core/package-lock.json
- boilerplate/ts/core/package.json
- boilerplate/ts/core/src/application/UseCase.ts
- boilerplate/ts/core/src/domain/commands/Command.ts
- boilerplate/ts/core/src/domain/context.ts
- boilerplate/ts/core/src/domain/messages/IMessage.ts
- boilerplate/ts/core/src/domain/messages/SystemEvent.ts
- boilerplate/ts/core/src/index.ts
- boilerplate/ts/core/yarn.lock
> changes for orchestrator support
